num =[4,6,2,4,5,7,8,9]
num.append(1)
print(num)
num.extend([3,8,2])
num.insert(0,7)
print(num)
num.remove(6)
print(num)
num.clear()
print(num)
num.pop()
print(num)
num.sort()
print(num)
num.sort(reverse=True)
print(num)
new = sorted(num)
print(new)
new = sorted(num,reverse=True)
print(new)
print(num.index(6))